### ISSUE TITLE
Custom elements in custom elements

### ISSUE THREAD

**Issue by magnessjo** [UMD-Digital/elements-alert-banner#2]
I think we should try to avoid custom elements in custom elements. `layout-lock` inside of the alert banner feels a paradox to me.  Edge may read that line and open a black hole that sucks in all existence.

**Comment by brionwolf** [comment]
Replaced `layout-lock` with a `div` element in [50e7896](https://github.com/UMD-Digital/elements-alert-banner/commit/50e789690d16d52dc5fe6fb1954fa2fe0115b235). If this works for you, feel free to close this.
