### ISSUE TITLE
Enhancement: Refactor display logic

### ISSUE THREAD

**Issue by magnessjo** [UMD-Digital/elements-alert-banner#3]
const alertContent = this.getAlertContent() as ElementContent;
      const stringifyContent = JSON.stringify(alertContent) as string;
      const storedContent = window.localStorage.getItem(storageKey);

      if (storedContent && stringifyContent === storedContent) {
        this.setAttribute('show', 'false');
        this.remove();
      }

      if (!storedContent || stringifyContent !== storedContent) {
        const shadowRoot = this.attachShadow({ mode: 'open' });
        const template = this.composeTemplate();

        shadowRoot.append(template.cloneNode(true));
        this.setAttribute('show', 'true');
      }

I find the logic hard to read.  I suggest modifying it to be something like 

```
displayAlertLogic() {

  const alertContent = this.getAlertContent() as ElementContent;
  const stringifyContenxt = JSON.stringify(alertContent) as string;
  const storedContent = window.localStorage.getItem(storageKey);

  const  showAlert = () => {
        const shadowRoot = this.attachShadow({ mode: 'open' });
        const template = this.composeTemplate();

        shadowRoot.append(template.cloneNode(true));
        this.setAttribute('show', 'true');
  }

  const  hideAlert = () => {
        this.setAttribute('show', 'false');
        this.remove();
  }

  if(!storedContent) {
    showAlert();
    return;
  }

  if(stringifyContent !== storedContent) {
    showAlert();
    return;
  }

  hideAlert();
}
```

**Comment by brionwolf** [comment]
Refactored into a `displayAlertLogic` method in 26b12a2 based on your suggestion.
